### ISSUE TITLE
All JavaScript loaded with page as <script> tags

### ISSUE THREAD

**Issue by Inumedia** [crrio/maple.fm#1]
This prohibits any caching from taking place on that JavaScript and should heavily be discouraged.

**Comment by corsair** [comment]
@Inumedia With this issue, are you referring to the market page's functions, or all scripts in general?

**Comment by Inumedia** [comment]
All JavaScript functionality that is literally being tossed into the page in <script></script> elements.

Not the <script src...> stuff

**Comment by corsair** [comment]
Fixed in #17.
