### ISSUE TITLE
Pagination number doesn't disappear after selection

### ISSUE THREAD

**Issue by Acen** [crrio/maple.fm#18]
Select new items per page option.
Disappears, reappears.

Either have it disappear permanently, or appear till clicked off?

Using desktop browser w/ mouse. Chrome.

![image](https://cloud.githubusercontent.com/assets/924120/21824668/558ccf26-d7e5-11e6-8292-44252f4fd415.png)

**Comment by corsair** [comment]
Nice catch, I had discovered this when I first began working on the new site but forgot to make an issue for it. The problem is related to Materalize's dropdown jQuery not firing it's "close" function.
