### ISSUE TITLE
Item detail shows bad info on hover

### ISSUE THREAD

**Issue by Acen** [crrio/maple.fm#19]
Mount a nebulite on a scroll? Sweet

![image](https://cloud.githubusercontent.com/assets/924120/21824725/9094c5f6-d7e5-11e6-91f7-a14dfa66bfe4.png)

Note this bad info isn't echoed on the item detail page.
http://dev.maple.fm/statistics/item/2049320

**Comment by corsair** [comment]
This is an issue currently effecting Item details on the live site (http://maple.fm/) as well unfortunately due to some issues defining what and what can't have nebulites from the API. Let me research this a bit more and try to find the actual cause.

**Comment by corsair** [comment]
For the time being, I've disabled nebulite information showing as the information we're able to work with via MapleStory.io's APIs don't give us enough information to be able to determine properly what nebulite is attached to the item, if it's an empty slot, or no slot at all.

Will be marking this as fixed as the issue of showing bad information is fixed, but will be revisited as a feature (feel free to add a feature request) in the future.
